# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meli_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meliaccount',
            old_name='author',
            new_name='owner',
        ),
    ]
