# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_account', '0003_meliaccount_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='meliaccount',
            name='access_token',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
