# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meli_account', '0004_meliaccount_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_from', to='meli_account.MeliAccount')),
                ('copy_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_to', to='meli_account.MeliAccount')),
            ],
        ),
    ]
