# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_account', '0005_copyaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyaccount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('running', 'Copiando'), ('done', 'Concluído')], default='pending', max_length=10),
        ),
    ]
